version: "3"
services:
  build_env:
    build: .
    container_name: image_viewer_rs_build_env
    tty: true
    volumes:
      - .:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /workspace/src-tauri
    environment:
      - DISPLAY=${DISPLAY}
      - NO_AT_BRIDGE=1
